// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // 1. For the App (Pooled - Port 6543)
    url: env("DATABASE_URL"),

    // 2. For the Build/CLI (Direct - Port 5432)
    directUrl: env("DIRECT_URL"),
  },
});